/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AppPontuacoesRouteImport } from './routes/_app.pontuacoes'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppArquitetosRouteImport } from './routes/_app.arquitetos'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPontuacoesRoute = AppPontuacoesRouteImport.update({
  id: '/pontuacoes',
  path: '/pontuacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppArquitetosRoute = AppArquitetosRouteImport.update({
  id: '/arquitetos',
  path: '/arquitetos',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arquitetos': typeof AppArquitetosRoute
  '/dashboard': typeof AppDashboardRoute
  '/pontuacoes': typeof AppPontuacoesRoute
  '/login': typeof AuthLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arquitetos': typeof AppArquitetosRoute
  '/dashboard': typeof AppDashboardRoute
  '/pontuacoes': typeof AppPontuacoesRoute
  '/login': typeof AuthLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/arquitetos': typeof AppArquitetosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/pontuacoes': typeof AppPontuacoesRoute
  '/_auth/login': typeof AuthLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/arquitetos' | '/dashboard' | '/pontuacoes' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/arquitetos' | '/dashboard' | '/pontuacoes' | '/login'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/arquitetos'
    | '/_app/dashboard'
    | '/_app/pontuacoes'
    | '/_auth/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pontuacoes': {
      id: '/_app/pontuacoes'
      path: '/pontuacoes'
      fullPath: '/pontuacoes'
      preLoaderRoute: typeof AppPontuacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/arquitetos': {
      id: '/_app/arquitetos'
      path: '/arquitetos'
      fullPath: '/arquitetos'
      preLoaderRoute: typeof AppArquitetosRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppArquitetosRoute: typeof AppArquitetosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPontuacoesRoute: typeof AppPontuacoesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArquitetosRoute: AppArquitetosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPontuacoesRoute: AppPontuacoesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
