/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authRegisterIndexRouteImport } from './routes/(auth)/register/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as appPointsIndexRouteImport } from './routes/(app)/points/index'
import { Route as appDashboardIndexRouteImport } from './routes/(app)/dashboard/index'
import { Route as appArchitectsIndexRouteImport } from './routes/(app)/architects/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterIndexRoute = authRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => authRouteRoute,
} as any)
const appPointsIndexRoute = appPointsIndexRouteImport.update({
  id: '/(app)/points/',
  path: '/points/',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardIndexRoute = appDashboardIndexRouteImport.update({
  id: '/(app)/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const appArchitectsIndexRoute = appArchitectsIndexRouteImport.update({
  id: '/(app)/architects/',
  path: '/architects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/architects/': typeof appArchitectsIndexRoute
  '/dashboard/': typeof appDashboardIndexRoute
  '/points/': typeof appPointsIndexRoute
  '/login/': typeof authLoginIndexRoute
  '/register/': typeof authRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/architects': typeof appArchitectsIndexRoute
  '/dashboard': typeof appDashboardIndexRoute
  '/points': typeof appPointsIndexRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(app)/architects/': typeof appArchitectsIndexRoute
  '/(app)/dashboard/': typeof appDashboardIndexRoute
  '/(app)/points/': typeof appPointsIndexRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/$'
    | '/architects/'
    | '/dashboard/'
    | '/points/'
    | '/login/'
    | '/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/architects'
    | '/dashboard'
    | '/points'
    | '/login'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/api/auth/$'
    | '/(app)/architects/'
    | '/(app)/dashboard/'
    | '/(app)/points/'
    | '/(auth)/login/'
    | '/(auth)/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  appArchitectsIndexRoute: typeof appArchitectsIndexRoute
  appDashboardIndexRoute: typeof appDashboardIndexRoute
  appPointsIndexRoute: typeof appPointsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof authRegisterIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/points/': {
      id: '/(app)/points/'
      path: '/points'
      fullPath: '/points/'
      preLoaderRoute: typeof appPointsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard/': {
      id: '/(app)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof appDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/architects/': {
      id: '/(app)/architects/'
      path: '/architects'
      fullPath: '/architects/'
      preLoaderRoute: typeof appArchitectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authRouteRouteChildren {
  authLoginIndexRoute: typeof authLoginIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginIndexRoute: authLoginIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  appArchitectsIndexRoute: appArchitectsIndexRoute,
  appDashboardIndexRoute: appDashboardIndexRoute,
  appPointsIndexRoute: appPointsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
